name: interiorapp_flutter_client
description: "interiorapp client"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # 라우팅
  go_router: ^14.8.1
  # 상태관리
  flutter_riverpod: ^2.6.1
  # 반응형 레이아웃
  flutter_screenutil: ^5.9.3
  # 네트워크
  dio: ^5.8.0+1
  # 캐싱
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  # 채팅 말풍선
  chat_bubbles: ^1.7.0
  # 환경변수 파일
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # lint
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  # assets
  # assets:
    # - assets/images/
